name: eda
channels:
  - conda-forge
  - defaults
dependencies:
  - jupyterlab=3.0.12
  - seaborn=0.11.1
  - pandas=1.2.3
  - pip=20.3.3
  - pandas-profiling=2.11.0
  - pyarrow=2.0
  # Downgraded jinja2 to fix issues with importing pandas_profiling.
  - jinja2=3.0.3
  - pip:
      - wandb==0.10.31